name: Publish on project 1

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "resource-pack/project-1/**"

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Print something
        run: echo "$(<./resource-pack/project-1/src/test.json)" 